name: dagger

on: [push]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go environment
        uses: actions/setup-go@v5.5.0
        with:
          go-version: '1.24.2'
      - name: Run Dagger
        run: "go run ./ci"
